[Infos]
Brand = "Siglent"
Device = "SDS1052DL+"

[Specs]
Channel = 2
ChannelColor = ["Red", "Yellow"]
LegacyFunctions = []
BlacklistedFUnctions = []

[Generator]
Enabled = false

[MixedSignal]
Enabled = false

[PowerAnalyser]
Enabled = false