[Infos]
Brand = "Siglent"
Device = "SDS1104X-U"

[Specs]
Channel = 4
ChannelColor = ["Red", "Yellow", "Blue", "Green"]
LegacyFunctions = []
BlacklistedFUnctions = []
impedance = [1000000]

[Generator]
Enabled = false

[MixedSignal]
Enabled = false

[PowerAnalyser]
Enabled = false