[Infos]
Brand = "Siglent"
Device = "SDS1202X"

[Specs]
Channel = 2
ChannelColor = ["Red", "Yellow"]
LegacyFunctions = []
BlacklistedFUnctions = []
impedance = [1000000]

[Generator]
Enabled = false

[MixedSignal]
Enabled = false

[PowerAnalyser]
Enabled = false