[Infos]
Brand = "Siglent"
Device = "SDS6058L"

[Specs]
Channels = 8
ChannelColor = ["Yellow", "Pink", "Light Blue", "Green", "Violet", "Blue", "Red", "Orange"]
LegacyFunctions = []
BlacklistedFUnctions = []
impedance = [1000000]

[Generator]
Enabled = false

[MixedSignal]
Enabled = false

[PowerAnalyser]
Enabled = false

