[Infos]
Brand = "Siglent"
Device = "SDS7604A-H12"

[Specs]
Channels = 4
ChannelColor = ["Red", "Yellow", "Blue", "Green"]
LegacyFunctions = []
BlacklistedFUnctions = []

[Generator]
Enabled = false

[MixedSignal]
Enabled = false

[PowerAnalyser]
Enabled = false

