[Infos]
Brand = "Siglent"
Device = "SDS822X-HD"

[Specs]
Channel = 2
ChannelColor = ["Red", "Yellow"]
LegacyFunctions = []
BlacklistedFUnctions = []
impedance = [1000000]

[Generator]
Enabled = true # Installed by default with the latest firmware

[MixedSignal]
Enabled = true # Installed by default with the latest firmware

[PowerAnalyser]
Enabled = false