[Infos]
Brand = "Siglent"
Device = "SDS824X-HD"

[Specs]
Channel = 4
ChannelColor = ["Red", "Yellow", "Blue", "Green"]
LegacyFunctions = []
BlacklistedFUnctions = []
impedance = [1000000]

[Generator]
Enabled = true # Installed by default with the latest firmware

[MixedSignal]
Enabled = true # Installed by default with the latest firmware

[PowerAnalyser]
Enabled = false